/**
 * Minecraft Mod Creator - Backend Server
 * Render.com'da calisacak sekilde tasarlandi
 * Asenkron islem: AI kod uret -> GitHub push -> Actions tetikle -> Status sorgula
 */

require("dotenv").config();
const express = require("express");
const cors = require("cors");
const axios = require("axios");
const path = require("path");

const GitHubHelper = require("./utils/github-helper");
const { generateWorkflow } = require("./utils/workflow-gen");
const {
  FABRIC_VERSIONS,
  getGradleProperties,
  getBuildGradle,
  getSettingsGradle,
  getFabricModJson,
  getMixinConfig
} = require("./utils/gradle-configs");

const app = express();
app.use(cors());
app.use(express.json({ limit: "50mb" }));
app.use(express.static(path.join(__dirname, "../frontend")));

const PORT = process.env.PORT || 3000;
const CEREBRAS_API_KEY = process.env.CEREBRAS_API_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPO = process.env.GITHUB_REPO;

// In-memory status store
const buildStatus = new Map();

// ============================================================
// CEREBRAS AI - Sistem Prompt Olusturucu
// ============================================================

function generateSystemPrompt(data) {
  const {
    minecraft_version,
    modloader,
    mod_types,
    features,
    mod_name,
    mod_description
  } = data;

  const config = FABRIC_VERSIONS[minecraft_version];
  const isUnobfuscated = config ? config.is_unobfuscated : false;
  const mappingsNote = isUnobfuscated
    ? "BU SURUM UNOBFUSCATED! Mojang official mappings kullan. Yarn YOK."
    : "Yarn mappings kullan.";

  const modId = mod_name
    ? mod_name.toLowerCase().replace(/[^a-z0-9]/g, "")
    : "examplemod";
  const className = mod_name
    ? mod_name.replace(/[^a-zA-Z0-9]/g, "")
    : "ExampleMod";

  return `Sen bir uzman Minecraft Fabric mod gelistiricisisin. Kullanicinin istegine gore Minecraft ${minecraft_version} icin calisir, derlenebilir Fabric mod kodlari uretirsin.

${mappingsNote}

KURALLAR:
1. SADECE kod dosyalari uret, aciklama, yorum, sohbet YAPMA.
2. HER dosyayi ayri ayri \`\`\`dil:dosya_yolu formatinda ver.
3. Kodlar DERLENEBILIR olmali, syntax hatasi olmamali.
4. Minecraft ${minecraft_version} ile uyumlu API'ler kullan.
5. Fabric API dependency kullan.
6. Mod ID: ${modId} (kucuk harf, bosluksuz)
7. Ana sinif: com.${modId}.${className}Mod

ISTENEN MOD TURLERI: ${mod_types.join(", ")}
ISTENEN OZELLIKLER: ${features.join(", ")}
MOD ADI: ${mod_name || "AI Generated Mod"}
ACIKLAMA: ${mod_description || "Generated by AI"}

URETMEN GEREKEN DOSYALAR:
- src/main/java/com/${modId}/${className}Mod.java (Ana mod sinifi)
- src/main/resources/fabric.mod.json
- src/main/resources/${modId}.mixins.json (Mixin kullaniyorsan)
- build.gradle
- gradle.properties
- settings.gradle
- src/main/resources/assets/${modId}/lang/en_us.json (Dil dosyasi)
- Ek Java siniflari (bloklar, itemlar, entity'ler vb.)

ONEMLI:
- Eger unobfuscated surum (26.1+) ise: imports'ta obfuscated isimler YOK. Mojang official names kullan.
- Eger obfuscated surum (1.21.11 ve alti) ise: Yarn mappings kullan.
- Her sinif icin dogru package deklarasyonu: package com.${modId};
- Mod initializer: public class ${className}Mod implements ModInitializer
- Registry kullanimi: Registry.register(Registries.ITEM, new Identifier("${modId}", "item_name"), ITEM_INSTANCE);

SIMDI KODLARI URET:`;
}

// ============================================================
// AI Yanitini Parse Et
// ============================================================

function parseAIResponse(responseText) {
  const files = [];
  const codeBlockRegex = /```(\w+)?(?::([\w/.\-_]+))?\n([\s\S]*?)```/g;
  let match;

  while ((match = codeBlockRegex.exec(responseText)) !== null) {
    const lang = match[1] || "java";
    const filePath = match[2];
    const content = match[3].trim();

    if (filePath) {
      files.push({
        path: filePath,
        content: content,
        language: lang
      });
    }
  }

  if (files.length === 0) {
    const cleanText = responseText
      .replace(/```[\w]*\n?/g, "")
      .replace(/```/g, "")
      .trim();
    if (cleanText) {
      files.push({
        path: "src/main/java/com/example/ExampleMod.java",
        content: cleanText,
        language: "java"
      });
    }
  }

  return files;
}

// ============================================================
// API ENDPOINTLERI
// ============================================================

app.post("/api/generate", async (req, res) => {
  const startTime = Date.now();
  const requestId = `req_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

  try {
    const {
      prompt,
      minecraft_version,
      modloader,
      mod_types,
      features,
      mod_name,
      mod_description
    } = req.body;

    if (!minecraft_version || !modloader) {
      return res.status(400).json({
        success: false,
        error: "Minecraft surumu ve modloader zorunlu."
      });
    }

    if (modloader !== "Fabric") {
      return res.status(400).json({
        success: false,
        error: "Su an sadece Fabric destekleniyor."
      });
    }

    const config = FABRIC_VERSIONS[minecraft_version];
    if (!config) {
      return res.status(400).json({
        success: false,
        error: `Desteklenmeyen Minecraft surumu: ${minecraft_version}`
      });
    }

    const modId = (mod_name || "aimod").toLowerCase().replace(/[^a-z0-9]/g, "");
    const branchName = `mod/${modId}_${Date.now()}`;
    const displayName = mod_name || `AI-Mod-${Date.now()}`;

    buildStatus.set(requestId, {
      status: "generating",
      branch: branchName,
      modName: displayName,
      version: minecraft_version,
      startTime,
      logs: ["🚀 Mod olusturma baslatildi..."]
    });

    // 1. AI'ya istek at
    console.log(`[${requestId}] Cerebras API'ye istek atiliyor...`);
    updateStatus(requestId, "🤖 Yapay zekaya istek gonderiliyor...");

    const systemPrompt = generateSystemPrompt({
      minecraft_version,
      modloader,
      mod_types: mod_types || [],
      features: features || [],
      mod_name: displayName,
      mod_description
    });

    const aiResponse = await axios.post(
      "https://api.cerebras.ai/v1/chat/completions",
      {
        model: "gpt-oss-120b",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: prompt || "Minecraft modu olustur." }
        ],
        max_tokens: 16000,
        temperature: 0.2
      },
      {
        headers: {
          Authorization: `Bearer ${CEREBRAS_API_KEY}`,
          "Content-Type": "application/json"
        },
        timeout: 120000
      }
    );

    const aiContent = aiResponse.data.choices[0].message.content;
    console.log(`[${requestId}] AI yaniti alindi, parse ediliyor...`);
    updateStatus(requestId, "✅ Yapay zeka cevap verdi! Dosyalar ayristiriliyor...");

    // 2. AI yanitini parse et
    let files = parseAIResponse(aiContent);

    if (files.length === 0) {
      return res.status(500).json({
        success: false,
        error: "AI'dan gecerli kod dosyasi alinamadi."
      });
    }

    console.log(`[${requestId}] ${files.length} dosya bulundu.`);
    updateStatus(requestId, `📁 ${files.length} adet dosya olusturuldu.`);

    // 3. Zorunlu dosyalari ekle
    const existingPaths = files.map(f => f.path);

    if (!existingPaths.includes("gradle.properties")) {
      files.push({
        path: "gradle.properties",
        content: getGradleProperties(minecraft_version),
        language: "properties"
      });
    }

    if (!existingPaths.includes("build.gradle")) {
      files.push({
        path: "build.gradle",
        content: getBuildGradle(minecraft_version, modId, displayName),
        language: "gradle"
      });
    }

    if (!existingPaths.includes("settings.gradle")) {
      files.push({
        path: "settings.gradle",
        content: getSettingsGradle(),
        language: "gradle"
      });
    }

    if (!existingPaths.some(p => p.includes("fabric.mod.json"))) {
      files.push({
        path: "src/main/resources/fabric.mod.json",
        content: getFabricModJson(minecraft_version, modId, displayName, mod_description),
        language: "json"
      });
    }

    if (!existingPaths.includes("gradlew")) {
      files.push({
        path: "gradlew",
        content: getGradleWrapperScript(),
        language: "bash"
      });
    }
    if (!existingPaths.includes("gradlew.bat")) {
      files.push({
        path: "gradlew.bat",
        content: getGradleWrapperBat(),
        language: "batch"
      });
    }
    if (!existingPaths.includes("gradle/wrapper/gradle-wrapper.properties")) {
      files.push({
        path: "gradle/wrapper/gradle-wrapper.properties",
        content: getGradleWrapperProperties(config.gradle_version),
        language: "properties"
      });
    }

    // 4. GitHub'a pushla
    console.log(`[${requestId}] GitHub'a pushlaniyor...`);
    updateStatus(requestId, "☁️ Dosyalar GitHub'a pushlaniyor...");

    const gh = new GitHubHelper(GITHUB_TOKEN, GITHUB_REPO);
    await gh.createBranch(branchName);
    console.log(`[${requestId}] Branch olusturuldu: ${branchName}`);

    const workflowContent = generateWorkflow(minecraft_version, branchName);
    files.push({
      path: ".github/workflows/build-mod.yml",
      content: workflowContent,
      language: "yaml"
    });

    const commitMessage = `[Fabric] ${displayName} - MC ${minecraft_version}`;
    await gh.pushFiles(files, branchName, commitMessage);
    console.log(`[${requestId}] ${files.length} dosya pushlandi.`);
    updateStatus(requestId, `✅ GitHub'a pushlandi! Commit: ${commitMessage}`);

    // 5. Hemen cevap don (asenkron)
    updateStatus(requestId, "🔨 GitHub Actions derlemeye basladi...");
    updateStatus(requestId, "⏳ Derleniyor... (2-5 dk surebilir)");

    pollWorkflowStatus(requestId, branchName, gh);

    return res.json({
      success: true,
      requestId,
      branch: branchName,
      modName: displayName,
      minecraft_version,
      modloader,
      fileCount: files.length,
      message: "Mod kodlari GitHub'a gonderildi! Derleme basladi.",
      status: "building",
      checkStatusUrl: `/api/status/${requestId}`
    });

  } catch (error) {
    console.error(`[${requestId}] HATA:`, error.message);
    updateStatus(requestId, `❌ HATA: ${error.message}`);

    return res.status(500).json({
      success: false,
      error: error.message,
      requestId
    });
  }
});

app.get("/api/status/:requestId", async (req, res) => {
  const { requestId } = req.params;
  const status = buildStatus.get(requestId);

  if (!status) {
    return res.status(404).json({
      success: false,
      error: "Boyle bir istek bulunamadi."
    });
  }

  if (status.status === "building" || status.status === "generating") {
    try {
      const gh = new GitHubHelper(GITHUB_TOKEN, GITHUB_REPO);
      const run = await gh.getWorkflowRun(status.branch);

      if (run) {
        status.workflowRunId = run.id;
        status.workflowStatus = run.status;
        status.workflowConclusion = run.conclusion;
        status.workflowUrl = run.html_url;

        if (run.status === "completed") {
          if (run.conclusion === "success") {
            status.status = "success";
            status.message = "✅ DERLEME BASARILI!";

            const artifacts = await gh.getArtifacts(run.id);
            if (artifacts.length > 0) {
              status.artifactId = artifacts[0].id;
              status.artifactName = artifacts[0].name;
              status.downloadUrl = gh.getArtifactDownloadUrl(artifacts[0].id);
            }
          } else {
            status.status = "failed";
            status.message = `❌ DERLEME BASARISIZ: ${run.conclusion}`;
          }
        } else {
          status.message = `⏳ Derleniyor... (${run.status})`;
        }
      }
    } catch (error) {
      console.error("Status sorgulama hatasi:", error.message);
    }
  }

  return res.json({
    success: true,
    status: status.status,
    modName: status.modName,
    version: status.version,
    branch: status.branch,
    logs: status.logs,
    downloadUrl: status.downloadUrl || null,
    workflowUrl: status.workflowUrl || null,
    message: status.message || ""
  });
});

app.get("/api/download/:requestId", async (req, res) => {
  const { requestId } = req.params;
  const status = buildStatus.get(requestId);

  if (!status || !status.downloadUrl) {
    return res.status(404).json({
      success: false,
      error: "Indirme linki henuz hazir degil."
    });
  }

  return res.json({
    success: true,
    downloadUrl: status.downloadUrl,
    artifactName: status.artifactName,
    modName: status.modName,
    version: status.version
  });
});

app.get("/api/versions", (req, res) => {
  const versionOrder = ["26.1.2", "26.1", "1.21.11", "1.21.10", "1.21.9", "1.21.8",
    "1.21.5", "1.21.4", "1.21.3", "1.21.1", "1.21", "1.20.6", "1.20.4",
    "1.20.2", "1.20.1", "1.20", "1.19.4", "1.19.3", "1.19.2", "1.18.2",
    "1.18.1", "1.17.1", "1.16.5", "1.16.4", "1.15.2", "1.14.4", "1.12.2",
    "1.8.9", "1.7.10"];

  const versions = versionOrder
    .filter(v => FABRIC_VERSIONS[v])
    .map(v => ({
      version: v,
      ...FABRIC_VERSIONS[v]
    }));

  return res.json({
    success: true,
    versions
  });
});

app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "../frontend/index.html"));
});

// ============================================================
// YARDIMCI FONKSIYONLAR
// ============================================================

function updateStatus(requestId, message) {
  const status = buildStatus.get(requestId);
  if (status) {
    status.logs.push(`[${new Date().toLocaleTimeString()}] ${message}`);
    console.log(`[${requestId}] ${message}`);
  }
}

async function pollWorkflowStatus(requestId, branchName, gh) {
  const maxAttempts = 60;
  let attempts = 0;

  const interval = setInterval(async () => {
    attempts++;
    const status = buildStatus.get(requestId);
    if (!status) {
      clearInterval(interval);
      return;
    }

    try {
      const run = await gh.getWorkflowRun(branchName);
      if (!run) {
        if (attempts >= 5) {
          updateStatus(requestId, "⏳ Workflow henuz baslamadi, bekleniyor...");
        }
        return;
      }

      status.workflowRunId = run.id;
      status.workflowStatus = run.status;
      status.workflowConclusion = run.conclusion;
      status.workflowUrl = run.html_url;

      if (run.status === "completed") {
        clearInterval(interval);

        if (run.conclusion === "success") {
          status.status = "success";
          status.message = "✅ DERLEME BASARILI!";
          updateStatus(requestId, "✅ DERLEME BASARILI! 🎉");

          const artifacts = await gh.getArtifacts(run.id);
          if (artifacts.length > 0) {
            status.artifactId = artifacts[0].id;
            status.artifactName = artifacts[0].name;
            status.downloadUrl = gh.getArtifactDownloadUrl(artifacts[0].id);
            updateStatus(requestId, "📦 Mod JAR'i hazir!");
          }
        } else {
          status.status = "failed";
          status.message = `❌ DERLEME BASARISIZ: ${run.conclusion}`;
          updateStatus(requestId, `❌ DERLEME BASARISIZ: ${run.conclusion}`);
        }
      } else {
        const dots = ".".repeat(attempts % 4);
        updateStatus(requestId, `⏳ Derleniyor${dots} (${run.status})`);
      }
    } catch (error) {
      console.error("Polling hatasi:", error.message);
    }

    if (attempts >= maxAttempts) {
      clearInterval(interval);
      updateStatus(requestId, "⏰ Zaman asimi: Derleme durumu manuel kontrol edilmeli.");
      const status = buildStatus.get(requestId);
      if (status) {
        status.status = "timeout";
        status.message = "⏰ Zaman asimi";
      }
    }
  }, 10000);
}

function getGradleWrapperScript() {
  return `#!/bin/sh
exec java -jar "$0" "$@"
`;
}

function getGradleWrapperBat() {
  return `@echo off
setlocal
set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%
set DEFAULT_JVM_OPTS=
if defined JAVA_HOME goto findJavaFromJavaHome
set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if "%ERRORLEVEL%" == "0" goto init
echo.
echo ERROR: JAVA_HOME is not set
echo.
goto fail
:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:\\=/%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe
if exist "%JAVA_EXE%" goto init
echo.
echo ERROR: JAVA_HOME is invalid
echo.
goto fail
:init
set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
:end
if "%ERRORLEVEL%"=="0" goto mainEnd
:fail
exit /b 1
:mainEnd
if "%OS%"=="Windows_NT" endlocal
:omega
`;
}

function getGradleWrapperProperties(gradleVersion) {
  return `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-${gradleVersion}-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`;
}

app.listen(PORT, () => {
  console.log("=================================");
  console.log("  MINECRAFT MOD CREATOR");
  console.log("  AI-Powered Fabric Mod Generator");
  console.log("=================================");
  console.log(`  Server: http://localhost:${PORT}`);
  console.log(`  Repo: ${GITHUB_REPO || "AYARLANMADI"}`);
  console.log("=================================");
});
